version: "3.3"
services:
  rmq1:
    container_name: rmq1
    hostname: rmq1
    image: rabbitmq:3.10-management
    ports:
      - 8081:15672
      - 5001:5672
    environment:
      - RABBITMQ_ERLANG_COOKIE=ABCDEFGH
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
    volumes:
      - ./config/rmq1/:/config/
    networks:
      - rabbits
  rmq2:
    container_name: rmq2
    hostname: rmq2
    image: rabbitmq:3.10-management
    ports:
      - 8082:15672
      - 5002:5672
    environment:
      - RABBITMQ_ERLANG_COOKIE=ABCDEFGH
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
    volumes:
      - ./config/rmq2/:/config/
    networks:
      - rabbits
  rmq3:
    container_name: rmq3
    hostname: rmq3
    image: rabbitmq:3.10-management
    ports:
      - 8083:15672
      - 5003:5672
    environment:
      - RABBITMQ_ERLANG_COOKIE=ABCDEFGH
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
    volumes:
      - ./config/rmq3/:/config/
    networks:
      - rabbits

networks:
  rabbits:
